### ISSUE TITLE
Ошибка при клике на таймлайне видео-виджета

### ISSUE THREAD

**Issue by A-Evseeva** [A-Evseeva/odoo_toonproject#54]
```
Error:
Uncaught TypeError: this._doDebouncedAction is not a function

http://rosmultfilm.ru:49394/web/content/660-9a4b619/web.assets_backend.js:1058
Traceback:
TypeError: this._doDebouncedAction is not a function
    at Class._onInput (http://rosmultfilm.ru:49394/web/content/660-9a4b619/web.assets_backend.js:1058:349)
    at HTMLSpanElement.<anonymous> (http://rosmultfilm.ru:49394/web/content/380-53862a6/web.assets_common.js:3643:11)
    at HTMLSpanElement.dispatch (http://rosmultfilm.ru:49394/web/content/380-53862a6/web.assets_common.js:892:451)
    at HTMLSpanElement.elemData.handle (http://rosmultfilm.ru:49394/web/content/380-53862a6/web.assets_common.js:865:173)
```

**Comment by A-Evseeva** [comment]
Похоже, что это происходит всегда, когда кликаешь видео в форме не на кнопке play.
И похоже, что это недоработка кастомного виджета: клик на видео воспринимается, как попытка что-то делать (редактировать) с виджетом, как таковым, который пытается вызывать какую-то свою незаданную функцию.

**Comment by A-Evseeva** [comment]
Кстати, в Фаерфоксе такого не происходит. А в Хроме и Опере -- да. То есть, можно предположить, что линейки Хромовского видео имеют свойство не обрывать обработку своего события или что-то в этом роде. Потому как переход к нужному кадру-то таки происходит, а уже потом (разумеется, мгновенно) вылезает ошибка.

**Comment by A-Evseeva** [comment]
Вылечено в 9de8ec9fab83e0602ccfe6982ead2a90d498044f
добавлением виджету обработки события 'click .video' (просто пустая функция)

**Comment by A-Evseeva** [comment]
Однако, после этого перестала работать обработка и всех других событий. Нужно ее тоже добавлять в виде методов, вызывающих родительские методы.

**Comment by A-Evseeva** [comment]
70fa6d941c96ecba955bd20d6c01cb94e4347620 было заменено объявление events виджета на расширение events родителя. И первоначальный баг вернулся.
Надо искать, из какого события вылетает баг, и переписывать код именно этого обработчика.

**Comment by A-Evseeva** [comment]
Поправлено c3ef24e6d1b54bc5cac633db39f544f24867f252
в обработку _onInput добвалено условие this.mode == "edit"
