### ISSUE TITLE
Разные цвета для авторов комментариев

### ISSUE THREAD

**Issue by A-Evseeva** [A-Evseeva/odoo_toonproject#67]
Присвоить каждому пользователю какой-то собственный цвет (задается пусть через свойства пользователя), и этим цветом помечать как текстовые комментарии, так и метки на таймлайне, соответствующие почеркушкам.

**Comment by A-Evseeva** [comment]
Набор из 21 разного цвета:
`distinctColors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#000000']`

**Comment by A-Evseeva** [comment]
Сделано в ветке commenting: c6842b2e87f884fc6a15ade5aa8eb005aa699faa

**Comment by A-Evseeva** [comment]
Проблема. Переопределение модели res.users привело к тому, что с обновленным дистрибутивом на некоторых (production) серваках Odoo выпадает с ошибкой вроде "не найдено поле res.users.color"
Пока что в ветке commenting-eugencorp все изменения на эту тему выброшены: здесь 4911a2241514372733112dcd2a42d9d1d03a4804 и еще немного здесь 3ca6b094a0bd39163d0594981c3668398b56924e

**Comment by A-Evseeva** [comment]
Не вполне понятно, как теперь воспроизвести эту ошибку на не-production сервере, где уже каким-то чудом создалось соответствующее поле.
Ну и в чем, собственно, дело. Возможно, надо наследовать не от res.users а от кого-то из их потомков?

**Comment by A-Evseeva** [comment]
Полностью ошибка:

```
2019-12-03 10:36:57,372 1950 ERROR odoo odoo.sql_db: bad query: b'SELECT "res_users"."id" as "id","res_users"."create_date" as "create_date","res_users"."login" as "login","res_users"."write_date" as "write_date","res_users"."company_id" as "company_id","res_users"."odoobot_state" as "odoobot_state","res_users"."create_uid" as "create_uid","res_users"."write_uid" as "write_uid","res_users"."color" as "color","res_users"."action_id" as "action_id","res_users"."signature" as "signature","res_users"."active" as "active","res_users"."notification_type" as "notification_type","res_users"."share" as "share","res_users"."partner_id" as "partner_id","res_users"."alias_id" as "alias_id" FROM "res_users" WHERE "res_users".id IN (2)'
ERROR: column res_users.color does not exist
LINE 1: ...reate_uid","res_users"."write_uid" as "write_uid","res_users...
                                                             ^
 
2019-12-03 10:36:57,378 1950 INFO odoo werkzeug: 127.0.0.1 - - [03/Dec/2019 10:36:57] "GET /web HTTP/1.1" 500 - 140 0.131 0.136
2019-12-03 10:36:57,415 1950 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/odoo/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('res.users(2,).partner_id', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandra/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/home/alexandra/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/server.py", line 409, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/home/alexandra/.local/lib/python3.6/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 457, in web_client
    context = request.env['ir.http'].webclient_rendering_context()
  File "/opt/odoo/odoo/addons/web/models/ir_http.py", line 18, in webclient_rendering_context
    'session_info': json.dumps(self.session_info()),
  File "/opt/odoo/odoo/addons/mail_bot/models/ir_http.py", line 11, in session_info
    res = super(Http, self).session_info()
  File "/opt/odoo/odoo/addons/web_tour/models/ir_http.py", line 12, in session_info
    result = super(Http, self).session_info()
  File "/opt/odoo/odoo/addons/base_setup/models/ir_http.py", line 11, in session_info
    result = super(IrHttp, self).session_info()
  File "/opt/odoo/odoo/addons/web/models/ir_http.py", line 34, in session_info
    "name": user.name,
  File "/opt/odoo/odoo/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 1045, in _compute_value
    self.compute(records)
  File "/opt/odoo/odoo/odoo/fields.py", line 609, in _compute_related
    values = [first(value[name]) for value in values]
  File "/opt/odoo/odoo/odoo/fields.py", line 609, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/opt/odoo/odoo/odoo/models.py", line 5117, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/odoo/odoo/odoo/fields.py", line 1088, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/odoo/odoo/models.py", line 2836, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/opt/odoo/odoo/odoo/addons/base/models/res_users.py", line 1197, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_users.py", line 418, in read
    return super(Users, self).read(fields=fields, load=load)
  File "/opt/odoo/odoo/odoo/models.py", line 2774, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odoo/odoo/addons/base/models/res_users.py", line 369, in _read_from_database
    super(Users, self)._read_from_database(field_names, inherited_field_names)
  File "/opt/odoo/odoo/odoo/models.py", line 2901, in _read_from_database
    cr.execute(query_str, params)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column res_users.color does not exist
LINE 1: ...reate_uid","res_users"."write_uid" as "write_uid","res_users...

```

**Comment by A-Evseeva** [comment]
[Есть мнение](https://www.odoo.com/forum/help-1/question/hi-everyone-here-i-need-the-solution-in-this-error-programmingerror-column-res-partner-instructor-does-not-exist-i-was-trying-to-inherit-res-partner-in-my-custom-module-129222), что от res_company, res_partner, res_users не так просто наследовать. Сначала надо вручную создавать новые поля в таблицах. 
Поэтому стоит продумать какой-то альтернативный метод.

**Comment by A-Evseeva** [comment]
Альтернатива -- это в любом случае создание какой-то дополнительной модели. Кстати, ее (доп. модель) придется создавать и для разных других свойств, например, для отправки уведомлений. Так что стоит с этого и начать.
Возможно, надо использовать _inherits= (кстати, так наследует собственно res.users от res.partner

**Comment by A-Evseeva** [comment]
Поправлено именно таким способом, здесь: 977b2af66ed88a2b2b55719933433206b96fdb73
